[package]
name = "fnumbuf"
version = "0.1.0"
authors = ["carrotflakes <carrotflakes@gmail.com>"]
edition = "2018"

[dependencies]
fnum = { git = "https://github.com/carrotflakes/fnum", branch = "main" }
